Implement automated Build
2023DD2480Group20/CI-Server pull request #23
Opened 2023-02-08 19:58 UTC by tanios13

2023-02-08 20:09 UTC, YavizGuldalf commented on app/src/main/java/ci/server/Build.java
> +    public Build(RepositoryBuilder repositoryBuilder){
This is ok but I think just giving the File as an argument instead of the repository builder makes more sense

2023-02-08 21:28 UTC, YavizGuldalf requested changes

2023-02-08 21:28 UTC, YavizGuldalf commented on app/src/main/java/ci/server/Build.java
> +            ProcessBuilder builder = new ProcessBuilder(command);
I don't think this works the way you think it works. Take a look at the [documentation for the ProcessBuilder class](https://docs.oracle.com/javase/8/docs/api/java/lang/ProcessBuilder.html). I think the list in the constructor just provides arguments, it does not provide a list of command to be executed one after another.

2023-02-08 23:23 UTC, tanios13 commented on app/src/main/java/ci/server/Build.java
> +    public Build(RepositoryBuilder repositoryBuilder){
yes, it was in case we might need the repo details, I will change it

2023-02-08 23:24 UTC, tanios13 commented on app/src/main/java/ci/server/Build.java
> +            ProcessBuilder builder = new ProcessBuilder(command);
oh okay, I should have wrote a test to test it locally

2023-02-09 12:46 UTC, YavizGuldalf commented
I'll test this to see if it works

2023-02-09 12:46 UTC, YavizGuldalf approved these changes

2023-02-09 12:47 UTC, merged